# Generated by Django 6.0.4 on 2026-04-23 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('national_id', 'National ID Verification'), ('academic', 'Academic Credential Verification'), ('integrity', 'Chapter Six Integrity Check')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_type', models.CharField(choices=[('national_id', 'National ID Verification'), ('academic', 'Academic Credential Verification'), ('integrity', 'Chapter Six Integrity Check')], max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_data', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('verification_date', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('verification_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_result', to='integrations.verificationrequest')),
            ],
        ),
    ]
