# Generated by Django 6.0.4 on 2026-04-23 08:43

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('portfolio_file', models.FileField(blank=True, null=True, upload_to='portfolios/')),
                ('additional_documents', models.JSONField(blank=True, default=list)),
                ('ai_score', models.DecimalField(blank=True, decimal_places=2, help_text='AI matching score (0-100)', max_digits=5, null=True)),
                ('ai_analysis', models.JSONField(blank=True, default=dict, help_text='AI analysis results')),
                ('skill_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('experience_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qualification_match_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('screening_notes', models.TextField(blank=True)),
                ('screening_flags', models.JSONField(blank=True, default=list, help_text='Issues flagged during screening')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('screening', 'AI Screening'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interview_completed', 'Interview Completed'), ('offer_extended', 'Offer Extended'), ('offer_accepted', 'Offer Accepted'), ('offer_declined', 'Offer Declined'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('review_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('is_anonymous', models.BooleanField(default=False, help_text='Hide applicant identity during initial screening')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='Internal notes vs applicant-facing comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recruitment.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('phone', 'Phone Screen'), ('video', 'Video Interview'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('panel', 'Panel Interview'), ('final', 'Final Interview')], max_length=20)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('location', models.CharField(blank=True, help_text='Physical location or meeting link', max_length=200)),
                ('meeting_link', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, help_text='Interview rating 1-5', null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('reject', 'Reject'), ('maybe', 'Consider'), ('strong_maybe', 'Strongly Consider'), ('hire', 'Hire')], max_length=20)),
                ('interview_notes', models.TextField(blank=True)),
                ('follow_up_actions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='recruitment.application')),
                ('interviewers', models.ManyToManyField(blank=True, related_name='interviews_assigned', to=settings.AUTH_USER_MODEL)),
                ('primary_interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='recruitment.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Job requirements and qualifications')),
                ('responsibilities', models.TextField(help_text='Key responsibilities')),
                ('qualifications', models.TextField(help_text='Required qualifications')),
                ('skills_required', models.JSONField(blank=True, default=list, help_text='List of required skills')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(blank=True, max_length=100)),
                ('country', django_countries.fields.CountryField(default='KE', max_length=2)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('volunteer', 'Volunteer')], default='full_time', max_length=20)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_salary_negotiable', models.BooleanField(default=True)),
                ('application_deadline', models.DateTimeField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in months for temporary positions', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('max_applications', models.IntegerField(blank=True, help_text='Maximum number of applications to accept', null=True)),
                ('auto_screening', models.BooleanField(default=True, help_text='Enable AI-powered screening')),
                ('require_cover_letter', models.BooleanField(default=True)),
                ('require_portfolio', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='recruitment.jobcategory')),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.jobpost'),
        ),
        migrations.CreateModel(
            name='RecruitmentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('time_to_hire', 'Time to Hire'), ('cost_per_hire', 'Cost per Hire'), ('application_rate', 'Application Rate'), ('conversion_rate', 'Conversion Rate'), ('diversity_metric', 'Diversity Metric'), ('quality_of_hire', 'Quality of Hire')], max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technical_skills', models.IntegerField(help_text='Rating 1-5')),
                ('communication_skills', models.IntegerField(help_text='Rating 1-5')),
                ('problem_solving', models.IntegerField(help_text='Rating 1-5')),
                ('cultural_fit', models.IntegerField(help_text='Rating 1-5')),
                ('overall_rating', models.IntegerField(help_text='Rating 1-5')),
                ('strengths', models.TextField(blank=True)),
                ('weaknesses', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('recommendation', models.CharField(choices=[('reject', 'Reject'), ('maybe', 'Consider'), ('strong_maybe', 'Strongly Consider'), ('hire', 'Hire')], max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='recruitment.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('interview', 'interviewer')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('job', 'applicant')},
        ),
    ]
