# Generated by Django 4.2.7 on 2026-08-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_grade',
            field=models.CharField(blank=True, help_text='Job grade level (e.g., NCPD 05)', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_reference',
            field=models.CharField(blank=True, help_text='Job reference number (e.g., VN00993)', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='positions',
            field=models.IntegerField(default=1, help_text='Number of positions available'),
        ),
    ]
