# Generated by Django 4.2.7 on 2026-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_jobpost_job_grade_jobpost_job_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='portfolio_file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
