# Generated by Django 4.2.7 on 2026-08-07 09:11

import apps.recruitment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_alter_application_portfolio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='portfolio_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.recruitment.models.application_upload_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.recruitment.models.application_upload_path),
        ),
    ]
