# Generated by Django 4.2.7 on 2026-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_academic_qualifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='declaration',
        ),
        migrations.AddField(
            model_name='user',
            name='declaration1',
            field=models.BooleanField(default=False, help_text='Information is true and correct'),
        ),
        migrations.AddField(
            model_name='user',
            name='declaration2',
            field=models.BooleanField(default=False, help_text='Consent to background checks'),
        ),
        migrations.AddField(
            model_name='user',
            name='declaration3',
            field=models.BooleanField(default=False, help_text='Consent to data processing'),
        ),
        migrations.AddField(
            model_name='user',
            name='declaration_date',
            field=models.DateField(blank=True, help_text='Date of declaration', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='place_of_declaration',
            field=models.CharField(blank=True, help_text='Place where declaration was made', max_length=200, null=True),
        ),
    ]
