# Generated by Django 4.2.7 on 2026-08-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_work_experiences_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_completion',
            field=models.IntegerField(default=0, help_text='Profile completion percentage (0-100)'),
        ),
    ]
