# Generated by Django 4.2.7 on 2026-08-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='user_files/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='user_files/'),
        ),
    ]
