# Generated by Django 4.2.7 on 2026-08-07 09:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_profile_picture_alter_user_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.users.models.user_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.users.models.user_upload_path),
        ),
    ]
