# Generated by Django 6.0.4 on 2026-04-23 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recruitment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_type', models.CharField(choices=[('cv_parser', 'CV Parser'), ('skill_matcher', 'Skill Matcher'), ('semantic_search', 'Semantic Search'), ('sentiment_analysis', 'Sentiment Analysis'), ('bias_detector', 'Bias Detector'), ('chatbot', 'Recruitment Chatbot')], max_length=30)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('provider', models.CharField(blank=True, help_text='e.g., OpenAI, HuggingFace', max_length=50)),
                ('model_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('cv_samples', 'CV Samples'), ('job_descriptions', 'Job Descriptions'), ('skill_mappings', 'Skill Mappings'), ('interview_outcomes', 'Interview Outcomes')], max_length=30)),
                ('raw_data', models.JSONField()),
                ('processed_data', models.JSONField(blank=True, null=True)),
                ('labels', models.JSONField(default=dict)),
                ('annotations', models.JSONField(default=list)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('used_in_training', models.BooleanField(default=False)),
                ('model_versions', models.JSONField(default=list)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('hiring_trend', 'Hiring Trend'), ('skill_gap', 'Skill Gap Analysis'), ('candidate_pool', 'Candidate Pool Analysis'), ('process_efficiency', 'Process Efficiency'), ('diversity_analysis', 'Diversity Analysis')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(default=list)),
                ('analysis_results', models.JSONField(default=dict)),
                ('confidence_level', models.DecimalField(decimal_places=4, max_digits=5)),
                ('recommendations', models.JSONField(default=list)),
                ('action_items', models.JSONField(default=list)),
                ('time_period', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('relevant_jobs', models.ManyToManyField(blank=True, to='recruitment.jobpost')),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='BiasDetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('job_description', 'Job Description'), ('evaluation', 'Candidate Evaluation'), ('interview_notes', 'Interview Notes')], max_length=30)),
                ('content_id', models.CharField(max_length=100)),
                ('original_text', models.TextField()),
                ('bias_flags', models.JSONField(default=list)),
                ('bias_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('bias_categories', models.JSONField(default=list)),
                ('suggestions', models.JSONField(default=list)),
                ('corrected_text', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel')),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('conversation_type', models.CharField(choices=[('pre_screening', 'Pre-screening'), ('application_help', 'Application Help'), ('faq', 'FAQ'), ('interview_prep', 'Interview Preparation')], max_length=30)),
                ('initial_query', models.TextField()),
                ('messages', models.JSONField(default=list)),
                ('extracted_info', models.JSONField(default=dict)),
                ('next_actions', models.JSONField(default=list)),
                ('satisfaction_score', models.IntegerField(blank=True, null=True)),
                ('resolution_status', models.CharField(choices=[('resolved', 'Resolved'), ('escalated', 'Escalated'), ('abandoned', 'Abandoned'), ('ongoing', 'Ongoing')], default='ongoing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(auto_now=True)),
                ('job_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CVParsingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='original_cvs/')),
                ('parsed_text', models.TextField()),
                ('structured_data', models.JSONField(default=dict)),
                ('contact_info', models.JSONField(default=dict)),
                ('education', models.JSONField(default=list)),
                ('experience', models.JSONField(default=list)),
                ('skills', models.JSONField(default=list)),
                ('certifications', models.JSONField(default=list)),
                ('confidence_score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('processing_time', models.DurationField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_parsing_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MatchingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_level', models.DecimalField(decimal_places=4, max_digits=5)),
                ('skill_match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('experience_match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('education_match_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('semantic_similarity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('additional_skills', models.JSONField(default=list)),
                ('matching_algorithm', models.CharField(max_length=50)),
                ('processing_time', models.DurationField()),
                ('recommendation', models.CharField(choices=[('reject', 'Reject'), ('consider', 'Consider'), ('strong_consider', 'Strongly Consider'), ('interview', 'Interview'), ('high_priority', 'High Priority')], max_length=20)),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.aimodel')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matching_result', to='recruitment.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobpost')),
            ],
        ),
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('skill', 'Skill'), ('job_description', 'Job Description'), ('resume_text', 'Resume Text'), ('qualification', 'Qualification')], max_length=20)),
                ('content_id', models.CharField(max_length=100)),
                ('text_content', models.TextField()),
                ('embedding', models.JSONField()),
                ('embedding_model', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('content_type', 'content_id')},
            },
        ),
    ]
